### PR TITLE
Add LitElement

### PR DESCRIPTION
**Pull request by YerkoPalma**
I'm still not sure if this should be under framework or libraries section.

### CODE REVIEW

**Comment by achou11** [comment]
Yeah definitely a little trickier to categorize. I was thinking that maybe adding another section, such as Components or Projects to capture something like this. The latter is pretty vague so not sure if it I'd go with that one. 

If I had to choose one of the existing sections, I'd probably add it under libraries, though that still doesn't feel quite right. Feel free to add another section if you think there's one that could work!

**Comment by YerkoPalma** [comment]
I think something like this should be fine

## Frameworks
## Component libraries
## Rendering libraries

Does that makes sense?

**Comment by achou11** [comment]
Works for me! 👍 I definitely intended to just have libraries consist of both rendering and component-specific links, but the separation is a better choice.

**Comment by kodedninja** [comment]
Wouldn't it make more sense to include `lit-html` then? In fact, that is the underlying renderer.

**Comment by YerkoPalma** [comment]
@kodedninja yeah, I was thinking in adding `nanohtml`, `nanocomponent` and `hui` in their respectives sections then :)

**Comment by kodedninja** [comment]
@YerkoPalma ah, allright, that's perfect. And maybe `nanomorph` to the renderer section, as that's one of the super-powers of the choo family 😄 

Update: But I don't know where would it fit perfectly.

**Comment by achou11** [comment]
> Wouldn't it make more sense to include `lit-html` then? In fact, that is the underlying renderer.

That's a good point. Have to put some thought into what's actually responsible for the rendering.

So if you really want to get technical, Frameworks can technically be a many-to-one relationship with Renderers 😅

**Comment by YerkoPalma** [comment]
IMO `nanomorph` isn't a renderer nor a component library. It's function is to get diffs and update tree DOMs. I'm not sure if it is a good fit here, it would at least require a new section

**Comment by kodedninja** [comment]
@YerkoPalma I'm just afraid that the repo will end up with 5 different modules using almost the same underlying technologies. But maybe this isn't bad. The more I think about the better it gets haha.

Out of curiosity: if `nanomorph` is just a function (which it is), would something like [`morfine`](https://github.com/kodedninja/morfine) be a simple renderer?

**Comment by achou11** [comment]
Agree with @kodedninja that this could get crazy if we're not careful with it. I also agree that it's not the worst thing to have the many-to-one relationship, as long as there's some idea of a limit and the repo doesn't become its own node_modules tree 😆

**Comment by YerkoPalma** [comment]
Mmm maybe the problem is that there are too many posible sections? Perhaps the Components and Libraries sections are just enough, if we need more details on what a library does we might classify them with emojis or subtext or something

What do you think?

**Comment by achou11** [comment]
@YerkoPalma I think that's a good move for the time being. Let's stick to Occam's razor 👍

**Comment by YerkoPalma** [comment]
Ok, so finally there are the original sections (Component and libraries) and more libraries will come in a separate PR

**Comment by achou11** [comment]
Great! Adding before we change our minds again haha. Thanks to you both!

**Pull request merged**
